CCACHE=ccache
MXX=/usr/bin/gcc
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
GC=/home/lc/.xmake/packages/g/go/1.11/c5156c97e2e9dec5edeaa17987d59d44/bin/go
AS=/usr/bin/gcc
MM=/usr/bin/gcc

SH=/usr/bin/g++
LD=/usr/bin/g++
GC_LD=/home/lc/.xmake/packages/g/go/1.11/c5156c97e2e9dec5edeaa17987d59d44/bin/go
AR=/usr/bin/ar

coroutine_channel_libfiber_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libfiber/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_channel_libfiber_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libfiber/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -lfiber -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_libfiber_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libfiber/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_libfiber_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libfiber/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -lfiber -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_channel_libmill_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libmill/1.18/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_channel_libmill_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libmill/1.18/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -lmill -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_boost_CXX=-fvisibility=hidden -Wall -O3 -std=c++11 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_boost_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_libmill_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libmill/1.18/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_libmill_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libmill/1.18/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -lmill -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
other_case2_test1_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
other_case2_test1_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_channel_libtask_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libtask/1.0/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_channel_libtask_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libtask/1.0/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltask -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
other_case1_test2_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
other_case1_test2_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_channel_go_GC=
coroutine_channel_go_GC-LD=-s
coroutine_switch_libco_CXX=-fvisibility=hidden -Wall -O3 -std=c++11 -I/home/lc/.xmake/packages/l/libco/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_libco_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libco/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -lcolib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_channel_tbox_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_channel_tbox_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_libgo_CXX=-fvisibility=hidden -Wall -O3 -std=c++11 -I/home/lc/.xmake/packages/l/libgo/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_libgo_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libgo/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -llibgo -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_coroutine_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/c/coroutine/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_coroutine_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/c/coroutine/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -lcoroutine -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_libaco_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libaco/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_libaco_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libaco/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -laco -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
other_case2_test2_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
other_case2_test2_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_channel_libgo_CXX=-fvisibility=hidden -Wall -O3 -std=c++11 -I/home/lc/.xmake/packages/l/libgo/master/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_channel_libgo_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libgo/master/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -llibgo -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_libtask_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/l/libtask/1.0/c5156c97e2e9dec5edeaa17987d59d44/include -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_libtask_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/l/libtask/1.0/c5156c97e2e9dec5edeaa17987d59d44/lib -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltask -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_tbox_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
coroutine_switch_tbox_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
other_case1_test1_CC=-fvisibility=hidden -Wall -O3 -std=c99 -I/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/include -m64 -I/usr/local/include -I/usr/include
other_case1_test1_LD=-s -fvisibility=hidden -L/home/lc/.xmake/packages/t/tbox/v1.6.3/fb5bfbfe2596e00c4a88f800049881fb/lib -ltbox -lpthread -ldl -lm -lc -m64 -L/usr/local/lib -L/usr/lib
coroutine_switch_go_GC=
coroutine_switch_go_GC-LD=-s

default:  coroutine_channel_libfiber coroutine_switch_libfiber coroutine_channel_libmill coroutine_switch_boost coroutine_switch_libmill other_case2_test1 coroutine_channel_libtask other_case1_test2 coroutine_channel_go coroutine_switch_libco coroutine_channel_tbox coroutine_switch_libgo coroutine_switch_coroutine coroutine_switch_libaco other_case2_test2 coroutine_channel_libgo coroutine_switch_libtask coroutine_switch_tbox other_case1_test1 coroutine_switch_go

all:  coroutine_channel_libfiber coroutine_switch_libfiber coroutine_channel_libmill coroutine_switch_boost coroutine_switch_libmill other_case2_test1 coroutine_channel_libtask other_case1_test2 coroutine_channel_go coroutine_switch_libco coroutine_channel_tbox coroutine_switch_libgo coroutine_switch_coroutine coroutine_switch_libaco other_case2_test2 coroutine_channel_libgo coroutine_switch_libtask coroutine_switch_tbox other_case1_test1 coroutine_switch_go

.PHONY: default all  coroutine_channel_libfiber coroutine_switch_libfiber coroutine_channel_libmill coroutine_switch_boost coroutine_switch_libmill other_case2_test1 coroutine_channel_libtask other_case1_test2 coroutine_channel_go coroutine_switch_libco coroutine_channel_tbox coroutine_switch_libgo coroutine_switch_coroutine coroutine_switch_libaco other_case2_test2 coroutine_channel_libgo coroutine_switch_libtask coroutine_switch_tbox other_case1_test1 coroutine_switch_go

coroutine_channel_libfiber: build/linux/x86_64/release/coroutine_channel_libfiber
build/linux/x86_64/release/coroutine_channel_libfiber: build/.objs/coroutine_channel_libfiber/linux/x86_64/release/src/coroutine/channel/libfiber/main.c.o
	@echo linking.release coroutine_channel_libfiber
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/coroutine_channel_libfiber build/.objs/coroutine_channel_libfiber/linux/x86_64/release/src/coroutine/channel/libfiber/main.c.o $(coroutine_channel_libfiber_LD) > build/.build.log 2>&1

build/.objs/coroutine_channel_libfiber/linux/x86_64/release/src/coroutine/channel/libfiber/main.c.o: src/coroutine/channel/libfiber/main.c
	@echo ccache compiling.release src/coroutine/channel/libfiber/main.c
	@mkdir -p build/.objs/coroutine_channel_libfiber/linux/x86_64/release/src/coroutine/channel/libfiber
	@/usr/bin/$(CCACHE) $(CC) -c $(coroutine_channel_libfiber_CC) -o build/.objs/coroutine_channel_libfiber/linux/x86_64/release/src/coroutine/channel/libfiber/main.c.o src/coroutine/channel/libfiber/main.c > build/.build.log 2>&1

coroutine_switch_libfiber: build/linux/x86_64/release/coroutine_switch_libfiber
build/linux/x86_64/release/coroutine_switch_libfiber: build/.objs/coroutine_switch_libfiber/linux/x86_64/release/src/coroutine/switch/libfiber/main.c.o
	@echo linking.release coroutine_switch_libfiber
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/coroutine_switch_libfiber build/.objs/coroutine_switch_libfiber/linux/x86_64/release/src/coroutine/switch/libfiber/main.c.o $(coroutine_switch_libfiber_LD) > build/.build.log 2>&1

build/.objs/coroutine_switch_libfiber/linux/x86_64/release/src/coroutine/switch/libfiber/main.c.o: src/coroutine/switch/libfiber/main.c
	@echo ccache compiling.release src/coroutine/switch/libfiber/main.c
	@mkdir -p build/.objs/coroutine_switch_libfiber/linux/x86_64/release/src/coroutine/switch/libfiber
	@/usr/bin/$(CCACHE) $(CC) -c $(coroutine_switch_libfiber_CC) -o build/.objs/coroutine_switch_libfiber/linux/x86_64/release/src/coroutine/switch/libfiber/main.c.o src/coroutine/switch/libfiber/main.c > build/.build.log 2>&1

coroutine_channel_libmill: build/linux/x86_64/release/coroutine_channel_libmill
build/linux/x86_64/release/coroutine_channel_libmill: build/.objs/coroutine_channel_libmill/linux/x86_64/release/src/coroutine/channel/libmill/main.c.o
	@echo linking.release coroutine_channel_libmill
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/coroutine_channel_libmill build/.objs/coroutine_channel_libmill/linux/x86_64/release/src/coroutine/channel/libmill/main.c.o $(coroutine_channel_libmill_LD) > build/.build.log 2>&1

build/.objs/coroutine_channel_libmill/linux/x86_64/release/src/coroutine/channel/libmill/main.c.o: src/coroutine/channel/libmill/main.c
	@echo ccache compiling.release src/coroutine/channel/libmill/main.c
	@mkdir -p build/.objs/coroutine_channel_libmill/linux/x86_64/release/src/coroutine/channel/libmill
	@/usr/bin/$(CCACHE) $(CC) -c $(coroutine_channel_libmill_CC) -o build/.objs/coroutine_channel_libmill/linux/x86_64/release/src/coroutine/channel/libmill/main.c.o src/coroutine/channel/libmill/main.c > build/.build.log 2>&1

coroutine_switch_boost: build/linux/x86_64/release/coroutine_switch_boost
build/linux/x86_64/release/coroutine_switch_boost: build/.objs/coroutine_switch_boost/linux/x86_64/release/src/coroutine/switch/boost/main.cpp.o
	@echo linking.release coroutine_switch_boost
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/coroutine_switch_boost build/.objs/coroutine_switch_boost/linux/x86_64/release/src/coroutine/switch/boost/main.cpp.o $(coroutine_switch_boost_LD) > build/.build.log 2>&1

build/.objs/coroutine_switch_boost/linux/x86_64/release/src/coroutine/switch/boost/main.cpp.o: src/coroutine/switch/boost/main.cpp
	@echo ccache compiling.release src/coroutine/switch/boost/main.cpp
	@mkdir -p build/.objs/coroutine_switch_boost/linux/x86_64/release/src/coroutine/switch/boost
	@/usr/bin/$(CCACHE) $(CXX) -c $(coroutine_switch_boost_CXX) -o build/.objs/coroutine_switch_boost/linux/x86_64/release/src/coroutine/switch/boost/main.cpp.o src/coroutine/switch/boost/main.cpp > build/.build.log 2>&1

coroutine_switch_libmill: build/linux/x86_64/release/coroutine_switch_libmill
build/linux/x86_64/release/coroutine_switch_libmill: build/.objs/coroutine_switch_libmill/linux/x86_64/release/src/coroutine/switch/libmill/main.c.o
	@echo linking.release coroutine_switch_libmill
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/coroutine_switch_libmill build/.objs/coroutine_switch_libmill/linux/x86_64/release/src/coroutine/switch/libmill/main.c.o $(coroutine_switch_libmill_LD) > build/.build.log 2>&1

build/.objs/coroutine_switch_libmill/linux/x86_64/release/src/coroutine/switch/libmill/main.c.o: src/coroutine/switch/libmill/main.c
	@echo ccache compiling.release src/coroutine/switch/libmill/main.c
	@mkdir -p build/.objs/coroutine_switch_libmill/linux/x86_64/release/src/coroutine/switch/libmill
	@/usr/bin/$(CCACHE) $(CC) -c $(coroutine_switch_libmill_CC) -o build/.objs/coroutine_switch_libmill/linux/x86_64/release/src/coroutine/switch/libmill/main.c.o src/coroutine/switch/libmill/main.c > build/.build.log 2>&1

other_case2_test1: build/linux/x86_64/release/other_case2_test1
build/linux/x86_64/release/other_case2_test1: build/.objs/other_case2_test1/linux/x86_64/release/src/other/case2/test1/main.c.o
	@echo linking.release other_case2_test1
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/other_case2_test1 build/.objs/other_case2_test1/linux/x86_64/release/src/other/case2/test1/main.c.o $(other_case2_test1_LD) > build/.build.log 2>&1

build/.objs/other_case2_test1/linux/x86_64/release/src/other/case2/test1/main.c.o: src/other/case2/test1/main.c
	@echo ccache compiling.release src/other/case2/test1/main.c
	@mkdir -p build/.objs/other_case2_test1/linux/x86_64/release/src/other/case2/test1
	@/usr/bin/$(CCACHE) $(CC) -c $(other_case2_test1_CC) -o build/.objs/other_case2_test1/linux/x86_64/release/src/other/case2/test1/main.c.o src/other/case2/test1/main.c > build/.build.log 2>&1

coroutine_channel_libtask: build/linux/x86_64/release/coroutine_channel_libtask
build/linux/x86_64/release/coroutine_channel_libtask: build/.objs/coroutine_channel_libtask/linux/x86_64/release/src/coroutine/channel/libtask/main.c.o
	@echo linking.release coroutine_channel_libtask
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/coroutine_channel_libtask build/.objs/coroutine_channel_libtask/linux/x86_64/release/src/coroutine/channel/libtask/main.c.o $(coroutine_channel_libtask_LD) > build/.build.log 2>&1

build/.objs/coroutine_channel_libtask/linux/x86_64/release/src/coroutine/channel/libtask/main.c.o: src/coroutine/channel/libtask/main.c
	@echo ccache compiling.release src/coroutine/channel/libtask/main.c
	@mkdir -p build/.objs/coroutine_channel_libtask/linux/x86_64/release/src/coroutine/channel/libtask
	@/usr/bin/$(CCACHE) $(CC) -c $(coroutine_channel_libtask_CC) -o build/.objs/coroutine_channel_libtask/linux/x86_64/release/src/coroutine/channel/libtask/main.c.o src/coroutine/channel/libtask/main.c > build/.build.log 2>&1

other_case1_test2: build/linux/x86_64/release/other_case1_test2
build/linux/x86_64/release/other_case1_test2: build/.objs/other_case1_test2/linux/x86_64/release/src/other/case1/test2/main.c.o
	@echo linking.release other_case1_test2
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/other_case1_test2 build/.objs/other_case1_test2/linux/x86_64/release/src/other/case1/test2/main.c.o $(other_case1_test2_LD) > build/.build.log 2>&1

build/.objs/other_case1_test2/linux/x86_64/release/src/other/case1/test2/main.c.o: src/other/case1/test2/main.c
	@echo ccache compiling.release src/other/case1/test2/main.c
	@mkdir -p build/.objs/other_case1_test2/linux/x86_64/release/src/other/case1/test2
	@/usr/bin/$(CCACHE) $(CC) -c $(other_case1_test2_CC) -o build/.objs/other_case1_test2/linux/x86_64/release/src/other/case1/test2/main.c.o src/other/case1/test2/main.c > build/.build.log 2>&1

coroutine_channel_go: build/linux/x86_64/release/coroutine_channel_go
build/linux/x86_64/release/coroutine_channel_go: build/.objs/coroutine_channel_go/linux/x86_64/release/src/coroutine/channel/go/__gc.o
	@echo linking.release coroutine_channel_go
	@mkdir -p build/linux/x86_64/release
	@$(GC_LD) tool link $(coroutine_channel_go_GC_LD) -o build/linux/x86_64/release/coroutine_channel_go build/.objs/coroutine_channel_go/linux/x86_64/release/src/coroutine/channel/go/__gc.o > build/.build.log 2>&1

